# Generated by Django 2.0.1 on 2018-01-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('cpu', models.CharField(max_length=50, null=True)),
                ('mem', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('loads', models.CharField(max_length=20)),
            ],
        ),
    ]
