# Generated by Django 2.0.1 on 2018-01-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='server',
            table='server',
        ),
    ]
