# Generated by Django 2.0.1 on 2018-01-27 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('department', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dashboard.Department', verbose_name='department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'default_related_name': 'profile',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
